// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/src/domain/use_case/get_popular_tv_series_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app/src/data/remote/model/request/movie_paginated_request_parameters.dart'
    as _i9;
import 'package:app/src/data/remote/model/request/tv_series_paginated_request_parameters.dart'
    as _i10;
import 'package:app/src/domain/model/base_tmdb_paginated_model.dart' as _i8;
import 'package:app/src/domain/model/movie_model.dart' as _i6;
import 'package:app/src/domain/model/tv_series_model.dart' as _i7;
import 'package:app/src/domain/repository/tmdb_repository.dart' as _i2;
import 'package:core/core.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TMDBRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTMDBRepository extends _i1.Mock implements _i2.TMDBRepository {
  MockTMDBRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<String>> createGuestSession() =>
      (super.noSuchMethod(
            Invocation.method(#createGuestSession, []),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i5.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#createGuestSession, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);

  @override
  _i3.Future<_i4.Result<List<_i6.MovieModel>>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i3.Future<_i4.Result<List<_i6.MovieModel>>>.value(
              _i5.dummyValue<_i4.Result<List<_i6.MovieModel>>>(
                this,
                Invocation.method(#getPopularMovies, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i6.MovieModel>>>);

  @override
  _i3.Future<_i4.Result<List<_i6.MovieModel>>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue: _i3.Future<_i4.Result<List<_i6.MovieModel>>>.value(
              _i5.dummyValue<_i4.Result<List<_i6.MovieModel>>>(
                this,
                Invocation.method(#getTopRatedMovies, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i6.MovieModel>>>);

  @override
  _i3.Future<_i4.Result<List<_i7.TVSeriesModel>>> getPopularTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTVSeries, []),
            returnValue: _i3.Future<_i4.Result<List<_i7.TVSeriesModel>>>.value(
              _i5.dummyValue<_i4.Result<List<_i7.TVSeriesModel>>>(
                this,
                Invocation.method(#getPopularTVSeries, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i7.TVSeriesModel>>>);

  @override
  _i3.Future<_i4.Result<List<_i7.TVSeriesModel>>> getTopRatedTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTVSeries, []),
            returnValue: _i3.Future<_i4.Result<List<_i7.TVSeriesModel>>>.value(
              _i5.dummyValue<_i4.Result<List<_i7.TVSeriesModel>>>(
                this,
                Invocation.method(#getTopRatedTVSeries, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i7.TVSeriesModel>>>);

  @override
  _i3.Future<_i4.Result<_i8.BaseTMDBPaginatedModel<_i6.MovieModel>>>
  searchMovies({required _i9.MoviePaginatedRequestParameters? params}) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [], {#params: params}),
            returnValue: _i3.Future<
              _i4.Result<_i8.BaseTMDBPaginatedModel<_i6.MovieModel>>
            >.value(
              _i5.dummyValue<
                _i4.Result<_i8.BaseTMDBPaginatedModel<_i6.MovieModel>>
              >(this, Invocation.method(#searchMovies, [], {#params: params})),
            ),
          )
          as _i3.Future<
            _i4.Result<_i8.BaseTMDBPaginatedModel<_i6.MovieModel>>
          >);

  @override
  _i3.Future<_i4.Result<_i8.BaseTMDBPaginatedModel<_i7.TVSeriesModel>>>
  searchTVSeries({required _i10.TVSeriesPaginatedRequestParameters? params}) =>
      (super.noSuchMethod(
            Invocation.method(#searchTVSeries, [], {#params: params}),
            returnValue: _i3.Future<
              _i4.Result<_i8.BaseTMDBPaginatedModel<_i7.TVSeriesModel>>
            >.value(
              _i5.dummyValue<
                _i4.Result<_i8.BaseTMDBPaginatedModel<_i7.TVSeriesModel>>
              >(
                this,
                Invocation.method(#searchTVSeries, [], {#params: params}),
              ),
            ),
          )
          as _i3.Future<
            _i4.Result<_i8.BaseTMDBPaginatedModel<_i7.TVSeriesModel>>
          >);
}
