import 'package:app/src/domain/model/movie_model.dart';
import 'package:app/src/domain/model/tv_series_model.dart';

class TestResources {
  static const mockMoviePaginatedResponse = {
    'results': [
      {
        "adult": false,
        "backdrop_path": "/path/to/backdrop.jpg",
        "genre_ids": [28, 12, 878],
        "id": 12345,
        "original_language": "en",
        "original_title": "Original Movie Title",
        "overview": "This is a short summary of the movie plot.",
        "popularity": 98.7,
        "poster_path": "/path/to/poster.jpg",
        "release_date": "2025-05-16",
        "title": "Movie Title",
        "video": false,
        "vote_average": 7.8,
        "vote_count": 1523,
      },
      {
        "adult": false,
        "backdrop_path": "/path/to/backdrop.jpg",
        "genre_ids": [28, 12, 878],
        "id": 12345,
        "original_language": "en",
        "original_title": "Original Movie Title",
        "overview": "This is a short summary of the movie plot.",
        "popularity": 98.7,
        "poster_path": "/path/to/poster.jpg",
        "release_date": "2025-05-16",
        "title": "Movie Title",
        "video": false,
        "vote_average": 7.8,
        "vote_count": 1523,
      },
      {
        "adult": false,
        "backdrop_path": "/path/to/backdrop.jpg",
        "genre_ids": [28, 12, 878],
        "id": 12345,
        "original_language": "en",
        "original_title": "Original Movie Title",
        "overview": "This is a short summary of the movie plot.",
        "popularity": 98.7,
        "poster_path": "/path/to/poster.jpg",
        "release_date": "2025-05-16",
        "title": "Movie Title",
        "video": false,
        "vote_average": 7.8,
        "vote_count": 1523,
      },
      {
        "adult": false,
        "backdrop_path": "/path/to/backdrop.jpg",
        "genre_ids": [28, 12, 878],
        "id": 12345,
        "original_language": "en",
        "original_title": "Original Movie Title",
        "overview": "This is a short summary of the movie plot.",
        "popularity": 98.7,
        "poster_path": "/path/to/poster.jpg",
        "release_date": "2025-05-16",
        "title": "Movie Title",
        "video": false,
        "vote_average": 7.8,
        "vote_count": 1523,
      },
    ],
    'page': 1,
    'total_pages': 1,
    'total_results': 1,
  };

  static const mockTVSeriesPaginatedResponse = {
    'results': [
      {
        "backdrop_path": "/path/to/tv/backdrop.jpg",
        "first_air_date": "2022-10-01",
        "genre_ids": [18, 9648, 80],
        "id": 67890,
        "name": "TV Series Name",
        "origin_country": ["US"],
        "original_language": "en",
        "original_name": "Original TV Series Name",
        "overview": "This is the overview of the TV series.",
        "popularity": 123.45,
        "poster_path": "/path/to/tv/poster.jpg",
        "vote_average": 8.3,
        "vote_count": 987,
      },
      {
        "backdrop_path": "/path/to/tv/backdrop.jpg",
        "first_air_date": "2022-10-01",
        "genre_ids": [18, 9648, 80],
        "id": 67890,
        "name": "TV Series Name",
        "origin_country": ["US"],
        "original_language": "en",
        "original_name": "Original TV Series Name",
        "overview": "This is the overview of the TV series.",
        "popularity": 123.45,
        "poster_path": "/path/to/tv/poster.jpg",
        "vote_average": 8.3,
        "vote_count": 987,
      },
      {
        "backdrop_path": "/path/to/tv/backdrop.jpg",
        "first_air_date": "2022-10-01",
        "genre_ids": [18, 9648, 80],
        "id": 67890,
        "name": "TV Series Name",
        "origin_country": ["US"],
        "original_language": "en",
        "original_name": "Original TV Series Name",
        "overview": "This is the overview of the TV series.",
        "popularity": 123.45,
        "poster_path": "/path/to/tv/poster.jpg",
        "vote_average": 8.3,
        "vote_count": 987,
      },
    ],
    'page': 1,
    'total_pages': 1,
    'total_results': 1,
  };

  static final List<MovieModel> mockMovieList = [
    MovieModel(
      adult: false,
      backdropPath: "/path/to/backdrop.jpg",
      genreIds: [28, 12, 878],
      id: 12345,
      originalLanguage: "en",
      originalTitle: "Original Movie Title",
      overview: "This is a short summary of the movie plot.",
      popularity: 98.7,
      posterPath: "/path/to/poster.jpg",
      releaseDate: "2025-05-16",
      title: "Movie Title",
      video: false,
      voteAverage: 7.8,
      voteCount: 1523,
    ),
    MovieModel(
      adult: false,
      backdropPath: "/path/to/backdrop.jpg",
      genreIds: [28, 12, 878],
      id: 12345,
      originalLanguage: "en",
      originalTitle: "Original Movie Title",
      overview: "This is a short summary of the movie plot.",
      popularity: 98.7,
      posterPath: "/path/to/poster.jpg",
      releaseDate: "2025-05-16",
      title: "Movie Title",
      video: false,
      voteAverage: 7.8,
      voteCount: 1523,
    ),
    MovieModel(
      adult: false,
      backdropPath: "/path/to/backdrop.jpg",
      genreIds: [28, 12, 878],
      id: 12345,
      originalLanguage: "en",
      originalTitle: "Original Movie Title",
      overview: "This is a short summary of the movie plot.",
      popularity: 98.7,
      posterPath: "/path/to/poster.jpg",
      releaseDate: "2025-05-16",
      title: "Movie Title",
      video: false,
      voteAverage: 7.8,
      voteCount: 1523,
    ),
  ];

  static final List<TVSeriesModel> mockTVSeriesList = [
    TVSeriesModel(
      backdropPath: "/path/to/tv/backdrop.jpg",
      firstAirDate: "2022-10-01",
      genreIds: [18, 9648, 80],
      id: 67890,
      name: "TV Series Name",
      originCountry: ["US"],
      originalLanguage: "en",
      originalName: "Original TV Series Name",
      overview: "This is the overview of the TV series.",
      popularity: 123.45,
      posterPath: "/path/to/tv/poster.jpg",
      voteAverage: 8.3,
      voteCount: 987,
    ),
    TVSeriesModel(
      backdropPath: "/path/to/tv/backdrop.jpg",
      firstAirDate: "2022-10-01",
      genreIds: [18, 9648, 80],
      id: 67890,
      name: "TV Series Name",
      originCountry: ["US"],
      originalLanguage: "en",
      originalName: "Original TV Series Name",
      overview: "This is the overview of the TV series.",
      popularity: 123.45,
      posterPath: "/path/to/tv/poster.jpg",
      voteAverage: 8.3,
      voteCount: 987,
    ),
    TVSeriesModel(
      backdropPath: "/path/to/tv/backdrop.jpg",
      firstAirDate: "2022-10-01",
      genreIds: [18, 9648, 80],
      id: 67890,
      name: "TV Series Name",
      originCountry: ["US"],
      originalLanguage: "en",
      originalName: "Original TV Series Name",
      overview: "This is the overview of the TV series.",
      popularity: 123.45,
      posterPath: "/path/to/tv/poster.jpg",
      voteAverage: 8.3,
      voteCount: 987,
    ),
  ];
}
