name: internationalization
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true

flutter_intl:
  enabled: true
  main_locale: pt_BR
  arb_dir: lib/src/l10n
  output_dir: lib/src/generated
  class_name: AppIntl
